---
#--------------------
# handler: 呼び出し元のタスクに変化があった場合のみ呼び出される
#--------------------
- name: Reload amazon-cloudwatch-agent for RHEL
  command: "{{ cwa_agent_ctl }} -a fetch-config -m {{ cwa_agent_mode }} -c file:{{ cwa_agent_config_file }} -s"
  notify: Leave a copy of configuration

# cwaサービスをリロードすると、cwaの設定ファイルが削除されてしまうので注意
- name: パッケージ amazon-cloudwatch-agent の設定ファイルを残しておく(RHELのみ)
  template:
    src: agent/cwa-config-for-rhel.json.j2
    dest: "{{ cwa_agent_config_file }}.cp"
    mode: 0644
    force: true
  listen: Leave a copy of configuration

- name: Reload amazon-cloudwatch-agent for Windows
  ansible.windows.win_powershell:
    script: |
      & "{{ cwa_ps_path }}" -a fetch-config -m {{ cwa_agent_mode }} -s -c file:{{ cwa_agent_config_file }}


- name: Reload logrotate
  command: "{{ cwa_logrotate_daemon }} -d {{ cwa_logrotate_config_file }}"